name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test

    - name: Archive artifacts
      run: |
        mkdir build
        dotnet publish -c Release -o ./build
        zip -r artifacts.zip build
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-files
        path: artifacts.zip
